name: eco_lift
description: A mobile app for garbage collection.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  http: ^1.3.0 # Fixed indentation
  google_maps_flutter: ^2.5.3
  geolocator: ^14.0.2
  geocoding: ^2.1.1
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  location: ^8.0.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  socket_io_client: ^3.1.2
  web_socket_channel: ^3.0.3
  flutter_local_notifications: ^19.4.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_polyline_points: ^3.0.1
  flutter_svg: ^2.2.0
  flutter_map_location_marker: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ecolift_logo.png
    - assets/images/ecolift_logo_without_name.png
    - assets/images/
